Full and microG packages: support Swipe libraries installation ; minor installer improvements

diff --git a/Overlay/META-INF/com/google/android/update-binary b/Overlay/META-INF/com/google/android/update-binary
--- a/Overlay/META-INF/com/google/android/update-binary
+++ b/Overlay/META-INF/com/google/android/update-binary
@@ -187,6 +187,7 @@ check_nanomodsetup () {
 	[ -z ${nanomod_init} ] && set_prop nanomod_init 1
 	[ -z ${nanomod_gsync} ] && set_prop nanomod_gsync 0
 	[ -z ${nanomod_forcesystem} ] && set_prop nanomod_forcesystem 0
+	[ -z ${nanomod_swipe} ] && set_prop nanomod_swipe 0
 
 	source ${nanomodsetup}
 }
@@ -417,7 +418,12 @@ install_init () {
 
 	INSTALLER=$TMPDIR/$MODID
 	mkdir -p ${INSTALLER}
-	cd ${INSTALLER}
+	cd ${INSTALLER} || error " !! failed to prepare environment!"
+
+	ui_print " > prepare installation"
+	unzip -o "$ZIP" "system/*"
+	unzip -o "$ZIP" "init.d/*"
+	unzip -o "$ZIP" "swipe/*"
 	unzip -o "$ZIP" ".nanomod*"
 }
 
@@ -542,6 +548,29 @@ install_misc () {
 			nanomod_install /system/etc/init.d/${init} ${INIT_BASE}/
 		done
 	else	ui_print " << without init scripts"
+	fi
+
+	if [ "${nanomod_swipe}" -eq 1 ]; then
+		ui_print " << with swipe libraries"
+		case ${ARCH} in
+			arm )
+				mkdir -p ${MODPATH}/system/lib
+				nanomod_install /swipe/arm/* /system/lib/
+			;;
+			arm64 )
+				mkdir -p ${MODPATH}/system/lib64
+				nanomod_install /swipe/arm64/* /system/lib64/
+			;;
+			x86 )
+				mkdir -p ${MODPATH}/system/lib
+				nanomod_install /swipe/x86/* /system/lib/
+			;;
+			x86_64 )
+				mkdir -p ${MODPATH}/system/lib64
+				nanomod_install /swipe/x86_64/* /system/lib64/
+			;;
+		esac
+	else	ui_print " << without swipe libraries"
 	fi
 }
 
@@ -805,14 +834,6 @@ ui_print " "
 if [ "${MODE}" = "MAGISK" ]; then
 	magisk_install_setup
 	magisk_install_preinst
-fi
-
-ui_print " > prepare installation"
-cd ${INSTALLER} || exit 1
-unzip -o "$ZIP" "system/*"
-unzip -o "$ZIP" "init.d/*"
-
-if [ "${MODE}" = "MAGISK" ]; then
 	magisk_install_dirs
 fi
 
