update F-Droid package to new install mechanism

diff --git a/fdroid/META-INF/com/google/android/update-binary b/fdroid/META-INF/com/google/android/update-binary
--- a/fdroid/META-INF/com/google/android/update-binary
+++ b/fdroid/META-INF/com/google/android/update-binary
@@ -326,37 +326,74 @@ install_init () {
 }
 
 install_fdroid () {
-	cp -r ${INSTALLER}/system/app/FDroid \
-		${MODPATH}/system/app/
-	cp -r ${INSTALLER}/system/priv-app/FDroidPrivileged \
-		${MODPATH}/system/priv-app/
-	set_perm_dir ${MODPATH}/system/app/FDroid
-	set_perm_dir ${MODPATH}/system/priv-app/FDroidPrivileged
+	nanomod_install /system/app/FDroid /system/app/
+	nanomod_install /system/priv-app/FDroidPrivileged /system/priv-app/
 }
 
 ##########################################################################################
-# System Mode: Record installed files
+# Advanced Installation Functions
 ##########################################################################################
 
 nanomod_install () {
-	source=$1
-	dest=$2
+	source=${INSTALLER}${1}
+	destination=${MODPATH}${2}
+	perm=$3
 
-	if [[ -d ${1} ]; then
-		cp -r ${1} ${MODPATH}/${2}
-	else	cp ${1} ${MODPATH}/${2}
+	if [[ -d ${source} ]]; then
+		echo "    dir: ${source} > ${destination}"
+		cp -r ${source} ${destination} || \
+			error " !! failed to install ${source} to ${destination}"
+		perm_x=dir
+	elif [[ -f ${source} ]]; then
+		echo "    file: ${source} > ${destination}" || \
+			error " !! failed to install ${source} to ${destination}"
+		cp ${source} ${destination}
+		nanomod_subsitute ${destination}
+		perm_x=file
+	else	error " !! file ${source} not found"
 	fi
 
+	case perm in
+		bin )	set_perm_bin ${destination} ;;
+		* )	case perm_x in
+				dir )	set_perm_dir ${destination} ;;
+				file )	set_perm_file ${destination} ;;
+			esac
+		;;
+	esac
+
 	if [ "${MODE}" = "SYSTEM" ]; then
-		find -type f "${MODPATH}/${2}" \
-			>> /system/.nanomod-list
+		find "${source}" -type f >> /system/.nanomod-list
+	fi
+}
+
+nanomod_subsitute () {
+	if grep -q @ZIPDIR@ ${1}; then
+		if [[ "${ZIPDIR}" == "/external_sd" ]]; then
+			# /external_sd is already know by `nanomod-overlay`
+			# no need to add it a second time
+			sed -e 's|@ZIPDIR@||' -i \
+			${MODPATH}/system/bin/nanomod-overlay
+		else
+			sed -e "s|@ZIPDIR@|${ZIPDIR}|" -i \
+				${MODPATH}/system/bin/nanomod-overlay
+		fi
+	fi
+
+	if grep -q @MODPATH@ ${1}; then
+		sed -e "s|@MODPATH@|${MODPATH}|" -i \
+			${MODPATH}/system/bin/nanomod-overlay*
 	fi
 }
 
 nanomod_finalize () {
-	if [ "${MODE}" = "SYTEM" ]; then
-		sort /system/.nanomod-list | uniq > /system/.nanomod-list.tmp
-		mv /system/.nanomod-list.tmp /system/.nanomod-list
+	if [ "${MODE}" = "SYSTEM" ]; then
+		sed -e "s,^${INSTALLER},,g" -i /system/.nanomod-list \
+			|| error " !! failed to create uninstaller information"
+		sort /system/.nanomod-list | uniq > /system/.nanomod-list.tmp \
+			|| error " !! failed to create uninstaller information"
+		mv /system/.nanomod-list.tmp /system/.nanomod-list \
+			|| error " !! failed to create uninstaller information"
 	fi
 }
 
@@ -449,6 +486,8 @@ fi
 if [ "$NO_NANOMODSETUP" -eq 1 ]; then
 	rm $nanomodsetup
 fi
+
+nanomod_finalize
 
 ui_print " "
 ui_print " Thanks for using NanoMod "
