further improve external_sd init script

diff --git a/Overlay/system/etc/init.d/external_sd b/Overlay/system/etc/init.d/external_sd
--- a/Overlay/system/etc/init.d/external_sd
+++ b/Overlay/system/etc/init.d/external_sd
@@ -2,6 +2,19 @@
 
 echo "external_sd init script"
 
+# retry 6 times, wait 5 seconds between each try
+count=0
+
+while [ ! -z $(mount | grep "on /mnt/media_rw") ]; do
+	count=$((count+1))
+	if [ ${count} -lt 7 ]; then
+		sleep 5
+	else
+		echo ">> no SD Card found"
+		exit 1
+	fi
+done
+
 media_rw=$(mount | grep "on /mnt/media_rw" | sed -e 's,.*/mnt,/mnt,g;s, type.*,,g')
 
 if [[ -d ${media_rw} ]]; then
