improve on-pc framework-patcher

diff --git a/framework-patcher b/framework-patcher
--- a/framework-patcher
+++ b/framework-patcher
@@ -2,7 +2,8 @@
 
 GITHUB_URL="https://github.com/Lanchon/haystack.git"
 PATCH_CORE="sigspoof-core"
-CWD="${PWD}"
+CWD=$(readlink -m "${BASH_SOURCE[0]}")
+CWD=$(dirname "${CWD}")
 
 error () {
 	echo -e "${@}"
@@ -68,30 +69,31 @@ if [[ "$OSTYPE" == "darwin"* ]]; then
 fi
 
 adb shell "umount /system"
-adb shell "mount -orw /system" || error "Failed to mount /system"
+adb shell "mount -orw /system" || error "Failed to mount /system read-write"
 
-"${PWD}/pull-fileset" mydevice || error "Failed to pull files from device!"
+"${CWD}/haystack/pull-fileset" mydevice || error "Failed to pull files from device!"
 
-"${PWD}/patch-fileset" "${PWD}/patches/${PATCH_HOOK}" \
-	"${API}" "${PWD}/mydevice" || \
+"${CWD}/haystack/patch-fileset" "${CWD}/haystack/patches/${PATCH_HOOK}" \
+	"${API}" "${CWD}/haystack/mydevice" || \
 	error "Failed applying sigspoof hook patch!"
 
-"${PWD}/patch-fileset" "${PWD}/patches/${PATCH_CORE}" "${API}" \
-	"${PWD}/mydevice__${PATCH_HOOK}" \
+"${CWD}/haystack/patch-fileset" "${CWD}/haystack/patches/${PATCH_CORE}" "${API}" \
+	"${CWD}/haystack/mydevice__${PATCH_HOOK}" \
 	|| error "Failed applying sigspoof core patch!"
 
-adb push "${PWD}/mydevice__${PATCH_HOOK}__${PATCH_CORE}/services.jar" \
+adb push "${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}/services.jar" \
 	/tmp/services.jar || error "Failed to push services.jar to device"
 
-adb push "${CWD}/remote.sh" /tmp/ || \
+adb push "${CWD}/framework-patcher-remote" /tmp/ || \
 	error "Failed to push helper script to device"
 
-adb shell "chmod 0755 /tmp/remote.sh" || \
+adb shell "chmod 0755 /tmp/framework-patcher-remote" || \
 	error "Failed to set permissions for helper script"
 
-adb shell "/tmp/remote.sh" || \
+adb shell "/tmp/framework-patcher-remote" || \
 	error "Failed to install services.jar"
 
 echo -e "\nNow reboot device and enjoy microG!"
 
+cd "${CWD}"
 rm -rf "${CWD}/haystack"
