FrameworkPatcher: drop UI support

diff --git a/framework-patcher b/framework-patcher
--- a/framework-patcher
+++ b/framework-patcher
@@ -30,8 +30,6 @@ there version is one of:
 	8.0	[O]
 	8.1	[O]
 
---gui	enables Signature Spoofing toggle in Developer Settings.
-
 your device must be in TWRP and connected to PC."
 
 exit 0
@@ -52,8 +50,6 @@ case "${1}" in
 	8.1 )	API=27	;;
 	*   )	help	;;
 esac
-
-[[ "${2}" == "--gui" && ${API} -lt 25 ]] && WITH_UI=1
 
 if [[ ${API} -lt 24 ]]; then
 	PATCH_HOOK="sigspoof-hook-4.1-6.0"
@@ -100,21 +96,9 @@ rm -rf "${CWD}/haystack/mydevice*"
 	"${CWD}/haystack/mydevice__${PATCH_HOOK}" \
 	|| error "Failed applying sigspoof core patch!"
 
-if [[ ${WITH_UI} -eq 1 ]]; then
-	"${CWD}/haystack/patch-fileset" "${CWD}/haystack/patches/${PATCH_UI}" "${API}" \
-		"${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}" \
-		|| error "Failed applying sigspoof ui patch!"
 
-	adb push "${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}__${PATCH_UI}/services.jar" \
-		/tmp/services.jar || error "Failed to push services.jar to device"
-
-	adb push "${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}__${PATCH_UI}/Settings.apk" \
-		/tmp/Settings.apk || error "Failed to push services.jar to device"
-
-else
-	adb push "${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}/services.jar" \
-		/tmp/services.jar || error "Failed to push services.jar to device"
-fi
+adb push "${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}/services.jar" \
+	/tmp/services.jar || error "Failed to push services.jar to device"
 
 adb push "${CWD}/framework-patcher-remote" /tmp/ || \
 	error "Failed to push helper script to device"
