on-pc framework-patcher: check for TWRP earlier and add --gui parameter, cleanup before (re-)patching

diff --git a/framework-patcher b/framework-patcher
--- a/framework-patcher
+++ b/framework-patcher
@@ -15,7 +15,7 @@ help () {
 echo -e "haystack framework patcher helper
 
 provide Android Version like:
-	framework-patcher.sh [version]
+	framework-patcher.sh [version] [--gui]
 
 there version is one of:
 	4.1	[JB]
@@ -27,6 +27,8 @@ there version is one of:
 	6.0	[MM]
 	7.0	[N]
 	7.1	[N]
+
+--gui	enables Signature Spoofing toggle in Developer Settings.
 
 your device must be in TWRP and connected to PC."
 
@@ -47,10 +49,17 @@ case "${1}" in
 	*   )	help	;;
 esac
 
+[[ "${2}" == "--gui" ]] && WITH_UI=1
+
 if [[ ${API} -lt 24 ]]; then
 	PATCH_HOOK="sigspoof-hook-4.1-6.0"
-else	PATCH_HOOK="sigspoof-hook-7.0-7.1"
+	PATCH_UI="sigspoof-ui-global-4.1-6.0"
+else
+	PATCH_HOOK="sigspoof-hook-7.0-7.1"
+	PATCH_UI="sigspoof-ui-global-7.0-7.1"
 fi
+
+adb shell "[[ -d /twres ]] && exit 0" || error "Device is not in TWRP!"
 
 if [[ -d ${CWD}/haystack/.git ]]; then
 	cd "${CWD}/haystack"
@@ -75,6 +84,7 @@ fi
 adb shell "umount /system"
 adb shell "mount -orw /system" || error "Failed to mount /system read-write"
 
+rm -rf "${CWD}/haystack/mydevice*"
 "${CWD}/haystack/pull-fileset" mydevice || error "Failed to pull files from device!"
 
 "${CWD}/haystack/patch-fileset" "${CWD}/haystack/patches/${PATCH_HOOK}" \
@@ -85,8 +95,21 @@ adb shell "mount -orw /system" || error "Failed to mount /system read-write"
 	"${CWD}/haystack/mydevice__${PATCH_HOOK}" \
 	|| error "Failed applying sigspoof core patch!"
 
-adb push "${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}/services.jar" \
-	/tmp/services.jar || error "Failed to push services.jar to device"
+if [[ ${WITH_UI} -eq 1 ]]; then
+	"${CWD}/haystack/patch-fileset" "${CWD}/haystack/patches/${PATCH_UI}" "${API}" \
+		"${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}" \
+		|| error "Failed applying sigspoof ui patch!"
+
+	adb push "${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}__${PATCH_UI}/services.jar" \
+		/tmp/services.jar || error "Failed to push services.jar to device"
+
+	adb push "${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}__${PATCH_UI}/Settings.apk" \
+		/tmp/Settings.apk || error "Failed to push services.jar to device"
+
+else
+	adb push "${CWD}/haystack/mydevice__${PATCH_HOOK}__${PATCH_CORE}/services.jar" \
+		/tmp/services.jar || error "Failed to push services.jar to device"
+fi
 
 adb push "${CWD}/framework-patcher-remote" /tmp/ || \
 	error "Failed to push helper script to device"
