update mount code in other parts aswell

diff --git a/systest/SysTest b/systest/SysTest
--- a/systest/SysTest
+++ b/systest/SysTest
@@ -37,30 +37,10 @@ is_mounted () {
 	return $?
 }
 
-# taken from Magisk, with minor modifications for NanoDroid
-mount_partitions () {
-	DEVICE_AB=FALSE
-	VENDOR_COMPAT=FALSE
-
-	SYSTEM_AS_ROOT=$(getprop ro.build.system_root_image)
-	SYSTEM_BLOCK=/dev/block/bootdevice/by-name/system
-
+mount_apex () {
 	APEX_FILE=""
 	APEX_DIR=""
 	APEX_LOOP=""
-
-	if [ "${SYSTEM_AS_ROOT}" == "true" ]; then
-		SLOT=$(grep_cmdline androidboot.slot_suffix)
-		if [ -n "${SLOT}" ]; then
-			DEVICE_AB=TRUE
-			SYSTEM_BLOCK=/dev/block/bootdevice/by-name/system${SLOT}
-		fi
-		SYSTEM_MOUNT=/system_root
-	else
-		SYSTEM_MOUNT=/system
-	fi
-
-	[ ! -f /system/build.prop ] && error "failed to mount /system (unsupported A/B device?)"
 
 	for apex in com.android.runtime com.android.runtime.release com.android.runtime.debug; do
 		if [ -f /system/apex/${apex}.apex ]; then
@@ -72,64 +52,70 @@ mount_partitions () {
 		fi
 	done
 
-	if [ -n "${APEX_FILE}" ]; then
-		mkdir -p /dev/tmp/apex
-		unzip "${RUNTIME_APEX}" -d /dev/tmp/apex
+	if ! ${BOOTMODE}; then
+		if [ -n "${APEX_FILE}" ]; then
+			mkdir -p /dev/tmp/apex
+			unzip "${APEX_FILE}" -d /dev/tmp/apex
 
-		mkdir -p /apex/com.android.runtime
-		mount -oloop,ro /dev/tmp/apex/apex_payload.img /apex/com.android.runtime
+			mkdir -p /apex/com.android.runtime
+			mount -oloop,ro /dev/tmp/apex/apex_payload.img /apex/com.android.runtime
 
-		APEX_LOOP=$(mount | awk '/com.android.runtime/{print $1}')
-	elif [ -n "${APEX_DIR}" ]; then
-		mkdir -p /apex
-		ln -sf "${APEX_DIR}" /apex/com.android.runtime
+			APEX_LOOP=$(mount | awk '/com.android.runtime/{print $1}')
+		elif [ -n "${APEX_DIR}" ]; then
+			mkdir -p /apex
+			ln -sf "${APEX_DIR}" /apex/com.android.runtime
+		fi
 	fi
+}
+
+# taken from Magisk, with minor modifications for NanoDroid
+mount_partitions () {
+	DEVICE_AB=FALSE
+	VENDOR_COMPAT=FALSE
+	SYSTEM_AS_ROOT=FALSE
+
+	SLOT=$(grep_cmdline androidboot.slot_suffix)
+	if [ -z ${SLOT} ]; then
+		SLOT=$(grep_cmdline androidboot.slot)
+		if [ -n ${SLOT} ]; then
+			SLOT=_${SLOT}
+			DEVICE_AB=TRUE
+		fi
+	fi
+
+	system_tmp=$(find /dev/block -type l -name system${SLOT} | head -n 1)
+	SYSTEM_BLOCK=$(readlink -f ${system_tmp})
 
 	is_mounted /data || mount /data || error "failed to mount /data!"
 
-	mount -o bind /dev/urandom /dev/random
-	! is_mounted ${SYSTEM_MOUNT} && mount -o rw ${SYSTEM_BLOCK} ${SYSTEM_MOUNT} || mount -o rw,remount ${SYSTEM_MOUNT}
+	${BOOTMODE} || mount -o bind /dev/urandom /dev/random
+	! is_mounted /system && mount -o rw ${SYSTEM_BLOCK} /system || mount -o rw,remount ${SYSTEM_BLOCK} /system
 
 	if [ -f /system/init.rc ]; then
+		SYSTEM_AS_ROOT=true
 		[ -L /system_root ] && rm -f /system_root
-		mkdir -p /system_root 2>/dev/null
+		mkdir /system_root 2>/dev/null
 		mount --move /system /system_root
 		mount -o bind /system_root/system /system
 	fi
 
-	[ ! -f /system/build.prop ] && error "failed to mount /system (unsupported A/B device?)"
-
-	if [ -f /system/apex/com.android.runtime.apex ]; then
-		RUNTIME_APEX="/system/apex/com.android.runtime.apex"
-	elif [ -f /system/apex/com.android.runtime.release.apex ]; then
-		RUNTIME_APEX="/system/apex/com.android.runtime.release.apex"
-	fi
-
-	if [ -n "${RUNTIME_APEX}" ]; then
-		mkdir -p /dev/tmp/apex
-		unzip "${RUNTIME_APEX}" -d /dev/tmp/apex
-
-		mkdir -p /apex/com.android.runtime
-
-		mount -oloop,ro /dev/tmp/apex/apex_payload.img /apex/com.android.runtime
-
-		APEX_LOOP=$(mount | awk '/com.android.runtime/{print $1}')
-	fi
-
-	! is_mounted /vendor && mount /vendor
+	vendor_tmp=$(find /dev/block -type l -name vendor${SLOT} | head -n 1)
+	VENDOR_BLOCK=$(readlink -f ${vendor_tmp})
 
 	if [ -L /system/vendor ]; then
-		if ! is_mounted /vendor; then
-			vendor_tmp=$(find /dev/block -type l -iname vendor${SLOT} | head -n 1)
-			VENDORBLOCK=$(readlink -f ${vendor_tmp})
-			mount -o ro ${VENDORBLOCK} /vendor
-		fi
+		! is_mounted /vendor && mount -o ro ${VENDOR_BLOCK} /vendor
 	elif [ -d /system/vendor ]; then
 		### XXX work-around required for some ROMs
 		VENDOR_COMPAT=TRUE
-		echo " xxx compat /vendor link created!"
+
+		! is_mounted /vendor && mount -o ro ${VENDOR_BLOCK} /vendor
+
 		ln -sf /system/vendor /vendor >/dev/null
 	fi
+
+	[ ! -f /system/build.prop ] && error "failed to mount /system (unsupported A/B device?)"
+
+	mount_apex
 
 	mount | awk '{print $1 " on " $3 " params: " $6}'
 }
diff --git a/uninstaller/META-INF/com/google/android/update-binary b/uninstaller/META-INF/com/google/android/update-binary
--- a/uninstaller/META-INF/com/google/android/update-binary
+++ b/uninstaller/META-INF/com/google/android/update-binary
@@ -114,42 +114,10 @@ error () {
 	exit 1
 }
 
-# taken from Magisk, with minor modifications for NanoDroid
-mount_partitions () {
-	DEVICE_AB=FALSE
-	VENDOR_COMPAT=FALSE
-
-	SYSTEM_AS_ROOT=$(getprop ro.build.system_root_image)
-	SYSTEM_BLOCK=/dev/block/bootdevice/by-name/system
-
+mount_apex () {
 	APEX_FILE=""
 	APEX_DIR=""
 	APEX_LOOP=""
-
-	if [ "${SYSTEM_AS_ROOT}" == "true" ]; then
-		SLOT=$(grep_cmdline androidboot.slot_suffix)
-		if [ -n "${SLOT}" ]; then
-			DEVICE_AB=TRUE
-			SYSTEM_BLOCK=/dev/block/bootdevice/by-name/system${SLOT}
-		fi
-		SYSTEM_MOUNT=/system_root
-	else
-		SYSTEM_MOUNT=/system
-	fi
-
-	is_mounted /data || mount /data || error "failed to mount /data!"
-
-	mount -o bind /dev/urandom /dev/random
-	! is_mounted ${SYSTEM_MOUNT} && mount -o rw ${SYSTEM_BLOCK} ${SYSTEM_MOUNT} || mount -o rw,remount ${SYSTEM_MOUNT}
-
-	if [ -f /system/init.rc ]; then
-		[ -L /system_root ] && rm -f /system_root
-		mkdir -p /system_root 2>/dev/null
-		mount --move /system /system_root
-		mount -o bind /system_root/system /system
-	fi
-
-	[ ! -f /system/build.prop ] && error "failed to mount /system (unsupported A/B device?)"
 
 	for apex in com.android.runtime com.android.runtime.release com.android.runtime.debug; do
 		if [ -f /system/apex/${apex}.apex ]; then
@@ -163,7 +131,7 @@ mount_partitions () {
 
 	if [ -n "${APEX_FILE}" ]; then
 		mkdir -p /dev/tmp/apex
-		unzip "${RUNTIME_APEX}" -d /dev/tmp/apex
+		unzip "${APEX_FILE}" -d /dev/tmp/apex
 
 		mkdir -p /apex/com.android.runtime
 		mount -oloop,ro /dev/tmp/apex/apex_payload.img /apex/com.android.runtime
@@ -173,21 +141,56 @@ mount_partitions () {
 		mkdir -p /apex
 		ln -sf "${APEX_DIR}" /apex/com.android.runtime
 	fi
+}
 
-	! is_mounted /vendor && mount /vendor
+# taken from Magisk, with minor modifications for NanoDroid
+mount_partitions () {
+	DEVICE_AB=FALSE
+	VENDOR_COMPAT=FALSE
+	SYSTEM_AS_ROOT=FALSE
+
+	SLOT=$(grep_cmdline androidboot.slot_suffix)
+	if [ -z ${SLOT} ]; then
+		SLOT=$(grep_cmdline androidboot.slot)
+		if [ -n ${SLOT} ]; then
+			SLOT=_${SLOT}
+			DEVICE_AB=TRUE
+		fi
+	fi
+
+	system_tmp=$(find /dev/block -type l -name system${SLOT} | head -n 1)
+	SYSTEM_BLOCK=$(readlink -f ${system_tmp})
+
+	is_mounted /data || mount /data || error "failed to mount /data!"
+
+	mount -o bind /dev/urandom /dev/random
+	! is_mounted /system && mount -o rw ${SYSTEM_BLOCK} /system || mount -o rw,remount ${SYSTEM_BLOCK} /system
+
+	if [ -f /system/init.rc ]; then
+		SYSTEM_AS_ROOT=true
+		[ -L /system_root ] && rm -f /system_root
+		mkdir /system_root 2>/dev/null
+		mount --move /system /system_root
+		mount -o bind /system_root/system /system
+	fi
+
+	vendor_tmp=$(find /dev/block -type l -name vendor${SLOT} | head -n 1)
+	VENDOR_BLOCK=$(readlink -f ${vendor_tmp})
 
 	if [ -L /system/vendor ]; then
-		if ! is_mounted /vendor; then
-			vendor_tmp=$(find /dev/block -type l -iname vendor${SLOT} | head -n 1)
-			VENDORBLOCK=$(readlink -f ${vendor_tmp})
-			mount -o ro ${VENDORBLOCK} /vendor
-		fi
+		! is_mounted /vendor && mount -o ro ${VENDOR_BLOCK} /vendor
 	elif [ -d /system/vendor ]; then
 		### XXX work-around required for some ROMs
 		VENDOR_COMPAT=TRUE
-		echo " xxx compat /vendor link created!"
+
+		! is_mounted /vendor && mount -o ro ${VENDOR_BLOCK} /vendor
+
 		ln -sf /system/vendor /vendor >/dev/null
 	fi
+
+	[ ! -f /system/build.prop ] && error "failed to mount /system (unsupported A/B device?)"
+
+	mount_apex
 
 	mount | awk '{print $1 " on " $3 " params: " $6}'
 }
@@ -359,9 +362,10 @@ rm -f /data/adb/.nanodroid_runtimeclean
 
 ui_print " >> clean up"
 
-umount -l /system_root 2>/dev/null
-umount -l /system 2>/dev/null
-umount -l /apex/com.android.runtime 2>/dev/null
+umount /system_root 2>/dev/null
+umount /system 2>/dev/null
+umount /vendor 2>/dev/null
+umount /apex/com.android.runtime 2>/dev/null
 losetup -d ${APEX_LOOP} 2>/dev/null
 
 ui_print " "
