migrate microG package to new installer

diff --git a/microG/META-INF/com/google/android/update-binary b/microG/META-INF/com/google/android/update-binary
--- a/microG/META-INF/com/google/android/update-binary
+++ b/microG/META-INF/com/google/android/update-binary
@@ -8,6 +8,7 @@ umask 022
 
 OUTFD=$2
 ZIP=$3
+ZIPDIR=$(dirname "${ZIP}")
 
 ##########################################################################################
 # Misc. Functions
@@ -452,22 +453,20 @@ install_init () {
 }
 
 install_microg () {
+	# install microG
 	for app in nlpBackendIchnaea nlpBackendNomiantim; do
-		cp -r ${INSTALLER}/system/app/${app} ${MODPATH}/system/app/
+		nanomod_install /system/app/${app} /system/app/
 	done
 	for app in DroidGuard GmsCore GsfProxy; do
-		cp -r ${INSTALLER}/system/priv-app/${app} \
-			${MODPATH}/system/priv-app/
+		nanomod_install /system/priv-app/${app} /system/priv-app/
 	done
 }
 
 install_mapsv1 () {
 	# install mapsv1 if requested
 	if grep -q nanomod.mapsv1=1 $nanomodsetup; then
-		cp -r ${INSTALLER}/system/etc/permissions/ ${MODPATH}/system/etc/
-		set_perm_data ${MODPATH}/system/etc/permissions/com.google.android.maps.xml
-		cp -r ${INSTALLER}/system/framework/ ${MODPATH}/system/
-		set_perm_data ${MODPATH}/system/framework/com.google.android.maps.jar
+		nanomod_install /system/etc/permissions/ /system/etc/
+		nanomod_install /system/framework/ /system/
 		ui_print " << with Maps API version 1"
 	else	ui_print " << without Maps API version 1"
 	fi
@@ -476,12 +475,9 @@ install_mapsv1 () {
 install_gsync () {
 	# install GSync if requested
 	if grep -q nanomod.gsync=1 $nanomodsetup; then
-		cp -r ${INSTALLER}/system/app/GoogleCalendarSync ${MODPATH}/system/app/
-		set_perm_dir ${MODPATH}/system/app/GoogleCalendarSync/
-		cp -r ${INSTALLER}/system/app/GoogleContactSync ${MODPATH}/system/app/
-		set_perm_dir ${MODPATH}/system/app/GoogleContactSync/
-		cp -r ${INSTALLER}/system/priv-app/GoogleBackupTransport ${MODPATH}/system/app/
-		set_perm_dir ${MODPATH}/system/app/GoogleBackupTransport/
+		nanomod_install /system/app/GoogleCalendarSync /system/app/
+		nanomod_install /system/app/GoogleContactSync /system/app/
+		nanomod_install /system/priv-app/GoogleBackupTransport /system/priv-app/
 		ui_print " << with Google Sync"
 	else	ui_print " << without Google Sync"
 	fi
@@ -490,17 +486,11 @@ install_gsync () {
 install_store () {
 	# install Yalp Store or Play Store whichever requested
 	if grep -q nanomod.play=1 $nanomodsetup; then
-		cp -r ${INSTALLER}/system/priv-app/Phonesky \
-			${MODPATH}/system/priv-app/
-		set_perm_dir ${MODPATH}/system/priv-app/Phonesky
+		nanomod_install /system/priv-app/Phonesky /system/priv-app/
 		ui_print " << with Play Store"
 	elif grep -q nanomod.play=2 $nanomodsetup; then
-		cp -r ${INSTALLER}/system/priv-app/FakeStore \
-			${MODPATH}/system/priv-app/
-		cp -r ${INSTALLER}/system/priv-app/YalpStore \
-			${MODPATH}/system/priv-app/
-		set_perm_dir ${MODPATH}/system/priv-app/YalpStore
-		set_perm_dir ${MODPATH}/system/priv-app/FakeStore
+		nanomod_install /system/priv-app/FakeStore /system/priv-app/
+		nanomod_install /system/priv-app/YalpStore /system/priv-app/
 		ui_print " << with Yalp Store"
 	else	ui_print " << without App Store"
 	fi
@@ -508,71 +498,85 @@ install_store () {
 
 install_misc () {
 	ui_print " < GNU Bash, NanoMod-Overlay"
-	cp ${INSTALLER}/system/etc/bash* ${MODPATH}/system/etc/
-	cp -r ${INSTALLER}/system/share ${MODPATH}/system/
-
-	set_perm_dir ${MODPATH}/system/share
-
-	for config in bashrc bash_logout; do
-		set_perm_data ${MODPATH}/system/etc/${config}
-	done
+	nanomod_install /system/etc/bash_logout /system/etc/
+	nanomod_install /system/etc/bashrc /system/etc/
+	nanomod_install /system/share /system/
 
 	for binary in nanomod-overlay nanomod-overlay.functions \
 		nanomod-overlay.addoverrides nanomod-overlay.genconfig \
 		nanomod-overlay.listoverrides nanomod-overlay.removeoverrides \
 		nanomod-overlay.shownonoverrides nanomod-overlay.updateoverrides \
 		nanomod-overlay.permission; do
-		cp ${INSTALLER}/system/bin/${binary} ${MODPATH}/system/bin/
-		set_perm_bin ${MODPATH}/system/bin/${binary}
+		nanomod_install /system/bin/${binary} /system/bin/ bin
 	done
 
 	# architecture dependend stuff
 	for binary in aapt bash bashbug; do
-		cp ${INSTALLER}/system/bin/${binary}.${BIN_ARCH} \
-			${MODPATH}/system/bin/${binary}
-		set_perm_bin ${MODPATH}/system/bin/${binary}
+		nanomod_install /system/bin/${binary}.${BIN_ARCH} /system/bin/${binary} bin
 	done
-
-
-	ZIPDIR=$(dirname "${ZIP}")
-	if [[ "${ZIPDIR}" == "/external_sd" ]]; then
-		# /external_sd is already know by `nanomod-overlay`
-		# no need to add it a second time
-		sed -e 's|@ZIPDIR@||' -i \
-		${MODPATH}/system/bin/nanomod-overlay
-	else
-		sed -e "s|@ZIPDIR@|${ZIPDIR}|" -i \
-			${MODPATH}/system/bin/nanomod-overlay
-	fi
-
-	sed -e "s|@MODPATH@|${MODPATH}|" -i \
-		${MODPATH}/system/bin/nanomod-overlay*
-
 }
 
 ##########################################################################################
-# System Mode: Record installed files
+# Advanced Installation Functions
 ##########################################################################################
 
 nanomod_install () {
-	source=$1
-	dest=$2
+	source=${INSTALLER}${1}
+	destination=${MODPATH}${2}
+	perm=$3
 
-	if [[ -d ${1} ]; then
-		cp -r ${1} ${MODPATH}/${2}
-	else	cp ${1} ${MODPATH}/${2}
+	if [[ -d ${source} ]]; then
+		echo "    dir: ${source} > ${destination}"
+		cp -r ${source} ${destination} || \
+			error " !! failed to install ${source} to ${destination}"
+		perm_x=dir
+	elif [[ -f ${source} ]]; then
+		echo "    file: ${source} > ${destination}"
+		cp ${source} ${destination} || \
+			error " !! failed to install ${source} to ${destination}"
+		nanomod_subsitute ${destination}
+		perm_x=file
+	else	error " !! file ${source} not found"
 	fi
 
+	case perm in
+		bin )	set_perm_bin ${destination} ;;
+		* )	case perm_x in
+				dir )	set_perm_dir ${destination} ;;
+				file )	set_perm_file ${destination} ;;
+			esac
+		;;
+	esac
+
 	if [ "${MODE}" = "SYSTEM" ]; then
-		find -type f "${MODPATH}/${2}" \
-			>> /system/.nanomod-list
+		find "${source}" -type f >> /system/.nanomod-list
+	fi
+}
+
+nanomod_subsitute () {
+	if grep -q @ZIPDIR@ ${1}; then
+		if [[ "${ZIPDIR}" == "/external_sd" ]]; then
+			# /external_sd is already know by `nanomod-overlay`
+			# no need to add it a second time
+			sed -e 's|@ZIPDIR@||' -i ${1}
+		else
+			sed -e "s|@ZIPDIR@|${ZIPDIR}|" -i ${1}
+		fi
+	fi
+
+	if grep -q @MODPATH@ ${1}; then
+		sed -e "s|@MODPATH@|${MODPATH}|" -i ${1}
 	fi
 }
 
 nanomod_finalize () {
-	if [ "${MODE}" = "SYTEM" ]; then
-		sort /system/.nanomod-list | uniq > /system/.nanomod-list.tmp
-		mv /system/.nanomod-list.tmp /system/.nanomod-list
+	if [ "${MODE}" = "SYSTEM" ]; then
+		sed -e "s,^${INSTALLER},,g" -i /system/.nanomod-list \
+			|| error " !! failed to create uninstaller information"
+		sort /system/.nanomod-list | uniq > /system/.nanomod-list.tmp \
+			|| error " !! failed to create uninstaller information"
+		mv /system/.nanomod-list.tmp /system/.nanomod-list \
+			|| error " !! failed to create uninstaller information"
 	fi
 }
 
@@ -688,6 +692,8 @@ fi
 if [ "$NO_NANOMODSETUP" -eq 1 ]; then
 	rm $nanomodsetup
 fi
+
+nanomod_finalize
 
 ui_print " "
 ui_print " Thanks for using NanoMod "
