patcher: support patching signature spoofing user interface in Developer Settings

diff --git a/patcher/META-INF/com/google/android/update-binary b/patcher/META-INF/com/google/android/update-binary
--- a/patcher/META-INF/com/google/android/update-binary
+++ b/patcher/META-INF/com/google/android/update-binary
@@ -63,7 +63,7 @@ request_size_check() {
 
 image_size_check() {
 	e2fsck -yf $1
-	curBlocks=`e2fsck -n $1 2>/dev/null | grep $1 | cut -d, -f3 | cut -d\  -f2`;
+	curBlocks=`e2fsck -n $1 2>/dev/null | grep $1 | cut -d, -f3 | cut -d\  -f2`
 	curUsedM=`echo "$curBlocks" | cut -d/ -f1`
 	curSizeM=`echo "$curBlocks" | cut -d/ -f1`
 	curFreeM=$(((curSizeM - curUsedM) * 4 / 1024))
@@ -151,9 +151,13 @@ detect_sdk () {
 	if [ "${SDK_VERSION}" -lt 24 ]; then
 		ui_print " > Android 4.1 - 6.0 (SDK ${SDK_VERSION}) detected"
 		PATCH_HOOK="hook_4.1-6.0_services.jar.dex"
+		PATCH_UI_SERVICES="ui_4.1-6.0_services.jar.dex"
+		PATCH_UI_SETTINGS="ui_4.1-6.0_Settings.apk.dex"
 	else
 		ui_print " > Android 7.x (SDK ${SDK_VERSION}) detected"
 		PATCH_HOOK="hook_7.x_services.jar.dex"
+		PATCH_UI_SERVICES="ui_7.x_services.jar.dex"
+		PATCH_UI_SETTINGS="ui_7.x_Settings.apk.dex"
 	fi
 
 	if [ "${SDK_VERSION}" -gt 21 ]; then
@@ -246,70 +250,116 @@ setup_patcher () {
 
 patch_services () {
 	ui_print " "
-	ui_print " > patching services.jar"
+	ui_print " > patching signature spoofing support"
 	ui_print " "
-	ui_print " << this might take a few minutes,"
-	ui_print " << depending on your device's power"
+	ui_print " << this might take a few minutes!"
 	ui_print " "
 
 	cp /system/framework/services.jar \
 		${TMPDIR}/services.jar || \
 		error " !! failed to copy services.jar"
 
-	ui_print " >> [1/2] applying hook patch"
+	ui_print " >> [1/2] applying hook patch (services.jar)"
 	apply_patch ${TMPDIR}/services.jar-hook \
 		${TMPDIR}/services.jar \
 		"${BASEDIR}/${PATCH_HOOK}" \
 		" !! failed to apply ${PATCH_HOOK}"
 
-	ui_print " >> [2/2] applying core patch"
+	ui_print " >> [2/2] applying core patch (services.jar)"
 	apply_patch ${TMPDIR}/services.jar-hook-core \
 		${TMPDIR}/services.jar \
 		"${BASEDIR}/${PATCH_CORE}" \
 		" !! failed to apply ${PATCH_CORE}"
+
+}
+
+patch_services_ui () {
+	cp /system/priv-app/Settings/Settings.apk \
+		${TMPDIR}/Settings.apk || \
+		error " !! failed to copy Settings.apk"
+
+	ui_print " "
+	ui_print " > patching signature spoofing user interface"
+	ui_print " "
+	ui_print " << this might take a few minutes!"
+	ui_print " "
+
+	ui_print " >> [1/2] applying ui patch (services.jar)"
+	apply_patch ${TMPDIR}/services.jar-hook-core-ui \
+		${TMPDIR}/services.jar \
+		"${BASEDIR}/${PATCH_UI_SERVICES}" \
+		" !! failed to apply ${PATCH_UI_SERVICES}"
+
+	ui_print " >> [2/2] applying ui patch (Settings.apk)"
+	apply_patch ${TMPDIR}/Settings.apk-ui \
+		${TMPDIR}/Settings.apk \
+		"${BASEDIR}/${PATCH_UI_SETTINGS}" \
+		" !! failed to apply ${PATCH_UI_SETTINGS}"
 }
 
 install_services () {
 	ui_print " "
 	if [ "${MODE}" = "SYSTEM" ]; then
 		ui_print " << backing up services.jar to: /sdcard"
-		cp /system/framework/services.jar /sdcard ||
+		cp /system/framework/services.jar /sdcard || \
 			error " !! failed to backup services.jar"
 
-		ui_print " << installing services.jar to: ROM"
-		install_path="${SYSPATH}/framework"
+		if [ "${nanomod_sigspoofui}" -eq 1 ]; then
+			ui_print " << backing up Settings.apk to: /sdcard"
+			cp /system/priv-app/Settings/Settings.apk /sdcard || \
+				error " !! failed to backup Settings.apk"
+		fi
 
-		echo /system/framework/services.jar >> \
-			${SYSPATH}/.nanomod-list
+		ui_print " << installing patched files to: ROM"
+		install_path="${SYSPATH}/"
 	else
 		if [ -d /dev/magisk_merge/NanoMod ]; then
-			ui_print " << installing services.jar to: NanoMod (full) [merge]"
+			ui_print " << installing patched files to: NanoMod (full) [merge]"
 			install_path="/magisk/NanoMod/system/framework/"
 		elif [ -d /dev/magisk_merge//NanoModmicroG ]; then
-			ui_print " << installing services.jar to: NanoMod (microG) [merge]"
-			install_path="/magisk/NanoModmicroG/system/framework/"
+			ui_print " << installing patched files to: NanoMod (microG) [merge]"
+			install_path="/magisk/NanoModmicroG/system/"
 		elif [ -d /magisk/NanoMod ]; then
-			ui_print " << installing services.jar to: NanoMod (full)"
-			install_path="/magisk/NanoMod/system/framework/"
+			ui_print " << installing patched files to: NanoMod (full)"
+			install_path="/magisk/NanoMod/system/"
 		elif [ -d /magisk/NanoModmicroG ]; then
-			ui_print " << installing services.jar to: NanoMod (microG)"
-			install_path="/magisk/NanoModmicroG/system/framework/"
+			ui_print " << installing patched files to: NanoMod (microG)"
+			install_path="/magisk/NanoModmicroG/system/"
 		else
 			ui_print " << backing up services.jar to: /sdcard"
-			cp /system/framework/services.jar /sdcard ||
+			cp /system/framework/services.jar /sdcard || \
 				error " !! failed to backup services.jar"
 
-			ui_print " << installing services.jar to: ROM"
-			install_path="${SYSPATH}/framework"
+			if [ "${nanomod_sigspoofui}" -eq 1 ]; then
+				ui_print " << backing up Settings.apk to: /sdcard"
+				cp /system/priv-app/Settings/Settings.apk /sdcard || \
+					error " !! failed to backup Settings.apk"
+			fi
 
-			echo /system/framework/services.jar >> \
-				${SYSPATH}/.nanomod-list
+			ui_print " << installing patched files to: ROM"
+			install_path="${SYSPATH}"
 		fi
 	fi
 
-	mkdir -p "${install_path}"
-	cp ${TMPDIR}/services.jar "${install_path}/" \
+	mkdir -p "${install_path}/framework"
+	cp ${TMPDIR}/services.jar "${install_path}/framework" \
 		|| error " !! failed to install services.jar"
+
+	if [ "${nanomod_sigspoofui}" -eq 1 ]; then
+		mkdir -p "${install_path}/priv-app/Settings"
+		cp ${TMPDIR}/Settings.apk "${install_path}/priv-app/Settings" \
+		|| error " !! failed to install Settings.apk"
+	fi
+
+	if [ "${install_path}" = "${SYSPATH}" ]; then
+		echo /system/framework/services.jar >> \
+			${SYSPATH}/.nanomod-list
+
+		if [ "${nanomod_sigspoofui}" -eq 1 ]; then
+			echo /system/priv-app/Settings/Settings.apk >> \
+			${SYSPATH}/.nanomod-list
+		fi
+	fi
 
 	touch ${SYSPATH}/.nanomod-patcher
 }
@@ -404,6 +454,11 @@ if [ -f ${IMG} ]; then
 fi
 
 patch_services
+
+if [ "${nanomod_sigspoofui}" -eq 1 ]; then
+	patch_services_ui
+fi
+
 install_services
 
 ui_print " "
diff --git a/uninstaller/META-INF/com/google/android/update-binary b/uninstaller/META-INF/com/google/android/update-binary
--- a/uninstaller/META-INF/com/google/android/update-binary
+++ b/uninstaller/META-INF/com/google/android/update-binary
@@ -145,6 +145,17 @@ if [ -f /system/.nanomod-list ]; then
 		sed '/\/system\/framework\/services.jar/d' -i /system/.nanomod-list
 	fi
 
+	# Settings.apk needs special treament
+	if grep -q /system/priv-app/Settings.apk/Settings.apk /system/.nanomod-list; then
+		if [ -f /sdcard/Settings.apk ]; then
+			ui_print " << restoring: unpatched Settings.apk"
+			mv /sdcard/Settings.apk /system/priv-app/Settings.apk/Settings.apk \
+				|| error " !! failed to restore Settings.apk"
+		else	ui_print " << can't restore unpatched Settings.apk"
+		fi
+		sed '/\/system\/priv-app\/Settings\/Settings.apk/d' -i /system/.nanomod-list
+	fi
+
 	xargs rm -f < /system/.nanomod-list \
 		|| " !! failed to remove files"
 	ui_print " << uninstalling: /system/.nanomod-list"
