patcher: support SecSettings.apk aswell

diff --git a/patcher/META-INF/com/google/android/update-binary b/patcher/META-INF/com/google/android/update-binary
--- a/patcher/META-INF/com/google/android/update-binary
+++ b/patcher/META-INF/com/google/android/update-binary
@@ -298,9 +298,16 @@ patch_services () {
 }
 
 patch_services_ui () {
-	cp /system/priv-app/Settings/Settings.apk \
-		${BASEDIR}/Settings.apk || \
-		error " !! failed to copy Settings.apk"
+	if [[ -f /system/priv-app/Settings/Settings.apk ]]; then
+		cp /system/priv-app/Settings/Settings.apk \
+			${BASEDIR}/Settings.apk || \
+			error " !! failed to copy Settings.apk"
+	elif [[ -f /system/priv-app/SecSettings/SecSettings.apk ]]; then
+		cp /system/priv-app/SecSettings/SecSettings.apk \
+			${BASEDIR}/SecSettings.apk || \
+			error " !! failed to copy SecSettings.apk"
+	else	error " !! neither Settings.apk nor SecSettings.apk found"
+	fi
 
 	ui_print " "
 	ui_print " > patching signature spoofing user interface"
@@ -369,8 +376,13 @@ install_services () {
 
 	if [ "${nanomod_sigspoofui}" -eq 1 ]; then
 		mkdir -p "${install_path}/priv-app/Settings"
-		cp ${BASEDIR}/Settings.apk "${install_path}/priv-app/Settings" \
-			|| error " !! failed to install Settings.apk"
+		if [[ -f ${BASEDIR}/Settings.apk ]]; then
+			cp ${BASEDIR}/Settings.apk "${install_path}/priv-app/Settings" \
+				|| error " !! failed to install Settings.apk"
+		elif [[ -f ${BASEDIR}/SecSettings.apk ]]; then
+			cp ${BASEDIR}/SecSettings.apk "${install_path}/priv-app/SecSettings" \
+				|| error " !! failed to install SecSettings.apk"
+		fi
 	fi
 
 	if [ "${install_path}" = "${SYSPATH}" ]; then
