patcher: revert back to custom Magisk functions

diff --git a/patcher/META-INF/com/google/android/update-binary b/patcher/META-INF/com/google/android/update-binary
--- a/patcher/META-INF/com/google/android/update-binary
+++ b/patcher/META-INF/com/google/android/update-binary
@@ -55,6 +55,29 @@ is_mounted() {
 	return $?
 }
 
+mount_image() {
+	if [ ! -d "$2" ]; then
+		mount -o rw,remount rootfs /
+		mkdir -p "$2" 2>/dev/null
+		$BOOTMODE && mount -o ro,remount rootfs /
+		[ ! -d "$2" ] && return 1
+	fi
+
+	if ! is_mounted "$2"; then
+		LOOPDEVICE=
+		for LOOP in 0 1 2 3 4 5 6 7; do
+			if ! is_mounted "$2"; then
+				LOOPDEVICE=/dev/block/loop$LOOP
+				[ -e $LOOPDEVICE ] || mknod $LOOPDEVICE b 7 $LOOP 2>/dev/null
+				losetup $LOOPDEVICE "$1" && mount -t ext4 -o loop $LOOPDEVICE "$2"
+				if is_mounted "$2"; then
+					break;
+				fi
+			fi
+		done
+	fi
+}
+
 error () {
 	ui_print "${@}"
 	if [ "${MODE}" = "MAGISK" ]; then
@@ -382,68 +405,56 @@ install_addond () {
 ##########################################################################################
 
 grow_magisk_img () {
-	e2fsck -yf ${IMG}
-	resize2fs -f ${IMG} ${newSizeM}M
-	e2fsck -yf ${IMG}
+	request_size_check /tmp/services.jar
+	image_size_check /data/magisk.img
+	if [ "$reqSizeM" -gt "$curFreeM" ]; then
+		SIZE=$(((reqSizeM + curUsedM) / 32 * 32 + 64))
+		resize2fs -f /data/magisk.img ${SIZE}M
+		e2fsck -yf /data/magisk.img
+	fi
 }
 
 shrink_magisk_img () {
-	e2fsck -yf ${IMG}
-	resize2fs -f ${IMG} ${newSizeM}M
-	e2fsck -yf ${IMG}
+	image_size_check /data/magisk.img
+	NEWDATASIZE=$((curUsedM / 32 * 32 + 32))
+	if [ "$curSizeM" -gt "$NEWDATASIZE" ]; then
+		resize2fs -f /data/magisk.img ${NEWDATASIZE}M
+		e2fsck -yf /data/magisk.img
+	fi
+}
+
+request_size_check() {
+	reqSizeM=`unzip -l "$1" 2>/dev/null | tail -n 1 | awk '{ print $1 }'`
+	reqSizeM=$((reqSizeM / 1048576 + 1))
+}
+
+image_size_check() {
+	e2fsck -yf $1
+	curBlocks=`e2fsck -n $1 2>/dev/null | grep $1 | cut -d, -f3 | cut -d\  -f2`;
+	curUsedM=`echo "$curBlocks" | cut -d/ -f1`
+	curSizeM=`echo "$curBlocks" | cut -d/ -f1`
+	curFreeM=$(((curSizeM - curUsedM) * 4 / 1024))
+	curUsedM=$((curUsedM * 4 / 1024 + 1))
+	curSizeM=$((curSizeM * 4 / 1024))
 }
 
 magisk_setup () {
-	ui_print " > setup Magisk environment"
-
-	MAGISKBIN=/data/magisk
-
-	[ -d $MAGISKBIN -a -f $MAGISKBIN/magisk -a -f $MAGISKBIN/util_functions.sh ] || \
-		error " !! Magisk version 13.1 or newer is required"
-
-	. $MAGISKBIN/util_functions.sh
-	[ ! -z $SCRIPT_VERSION -a $SCRIPT_VERSION -ge 1310 ] || \
-		error " !! Magisk version 13.1 or newer is required"
-
-	MOUNTPATH=/magisk
-	IMG=/data/magisk.img
-
-	if $BOOTMODE; then
-		MOUNTPATH=/dev/magisk_merge
-		IMG=/data/magisk_merge.img
-	fi
-
-	request_size_check "${BASEDIR}"
-
-	$BOOTMODE || recovery_actions
-
-	if [ -f "$IMG" ]; then
-		image_size_check "${IMG}"
-		if [ "$reqSizeM" -gt "$curFreeM" ]; then
-			newSizeM=$(((reqSizeM + curUsedM) / 32 * 32 + 64))
-			$MAGISKBIN/magisk --resizeimg $IMG $newSizeM || grow_magisk_img
-		fi
-	else
-		newSizeM=$((reqSizeM / 32 * 32 + 64))
-		$MAGISKBIN/magisk --createimg $IMG $newSizeM
-	fi
-
-	MAGISKLOOP=`$MAGISKBIN/magisk --mountimg $IMG $MOUNTPATH`
-	if ! is_mounted $MOUNTPATH; then
-		error " !! $IMG mount failed... abort"
+	if [ -f /data/magisk.img ]; then
+		grow_magisk_img || \
+			error " !! failed to grow magisk.img"
+		mount_image /data/magisk.img /magisk || \
+			error " !! failed to mount /magisk"
 	fi
 }
 
 magisk_cleanup () {
-	$MAGISKBIN/magisk --umountimg $MOUNTPATH $MAGISKLOOP
-
-	image_size_check $IMG
-	newSizeM=$((curUsedM / 32 * 32 + 64))
-	if [ $curSizeM -gt $newSizeM ]; then
-		$MAGISKBIN/magisk --resizeimg $IMG $newSizeM || shrink_magisk_img
+	if (is_mounted /magisk); then
+		umount /magisk
+		losetup -d $LOOPDEVICE
+		rmdir /magisk
+		shrink_magisk_img || \
+			error " !! failed to shrink magisk.img"
 	fi
-
-	$BOOTMODE || recovery_cleanup
 }
 
 ##########################################################################################
