add A/B partion scheme support (from Magisk)

diff --git a/Full/nanodroid-functions b/Full/nanodroid-functions
--- a/Full/nanodroid-functions
+++ b/Full/nanodroid-functions
@@ -111,14 +111,6 @@ show_banner () {
 	ui_print " "
 }
 
-check_system () {
-	is_mounted /system || mount -o ro /system 2>/dev/null
-	is_mounted /data || mount /data 2>/dev/null
-
-	[ ! -f '/system/build.prop' ] && \
-		error " !! /system/build.prop does not exist"
-}
-
 error () {
 	ui_print " !!"
 	ui_print "${@}"
@@ -132,6 +124,45 @@ error () {
 	nanodroid_storelogs
 
 	exit 1
+}
+
+# taken from Magisk, with minor modifications for NanoDroid
+mount_all_partitions () {
+	SLOT=$(getprop ro.boot.slot_suffix)
+	if [ -z ${SLOT} ]; then
+		SLOT=$(getprop ro.boot.slot)
+		[ ${SLOT} = "_" ] && SLOT=
+	fi
+
+	is_mounted /data || mount /data 2>/dev/null
+
+	${BOOTMODE} || mount -o bind /dev/urandom /dev/random
+
+	is_mounted /system || [ -f /system/build.prop ] || mount -o ro /system 2>/dev/null
+
+	if ! is_mounted /system && ! [ -f /system/build.prop ]; then
+		SYSTEMBLOCK=$(find /dev/block -iname system${SLOT} | head -n 1)
+		mount -t ext4 -o ro $SYSTEMBLOCK /system
+	fi
+
+	is_mounted /system || [ -f /system/build.prop ] || error "failed to mount /system"
+
+	cat /proc/mounts | grep -E '/dev/root|/system_root' >/dev/null && SKIP_INITRAMFS=true || SKIP_INITRAMFS=false
+	if [ -f /system/init.rc ]; then
+		SKIP_INITRAMFS=true
+		mkdir /system_root 2>/dev/null
+		mount --move /system /system_root
+		mount -o bind /system_root/system /system
+	fi
+
+	if [ -L /system/vendor ]; then
+		is_mounted /vendor || mount -o ro /vendor 2>/dev/null
+			if ! is_mounted /vendor; then
+			VENDORBLOCK=$(find /dev/block -iname vendor${SLOT} | head -n 1)
+			mount -t ext4 -o ro ${VENDORLOCK} /vendor
+		fi
+		is_mounted /vendor || error "failed to mount /vendor"
+	fi
 }
 
 detect_mode () {
@@ -169,8 +200,13 @@ detect_mode () {
 			;;
 		esac
 	else
-		mount -orw,remount /system 2>/dev/null || \
-			error " !! failed to re-mount /system read-write"
+		if is_mounted /system_root; then
+			mount -orw,remount /system_root 2>/dev/null || \
+				error " !! failed to re-mount /system read-write"
+		else
+			mount -orw,remount /system 2>/dev/null || \
+				error " !! failed to re-mount /system read-write"
+		fi
 		unset MODPATH
 	fi
 }
@@ -230,7 +266,13 @@ nanodroid_finalize () {
 	nanodroid_storelogs
 	[ "${MODE}" = "MAGISK" ] && magisk_install_finish
 	rm -rf ${INSTALLER}
-	${BOOTMODE} || umount /system 2>/dev/null
+
+	if ! ${BOOTMODE} ; then
+		umount -l /system_root 2>/dev/null
+		umount -l /system 2>/dev/null
+		umount -l /vendor 2>/dev/null
+		umount -l /dev/random 2>/dev/null
+	fi
 
 	ui_print " "
 	ui_print " Thanks for using NanoDroid "
