final fixes for nanmod_libs()

diff --git a/Full/META-INF/com/google/android/update-binary b/Full/META-INF/com/google/android/update-binary
--- a/Full/META-INF/com/google/android/update-binary
+++ b/Full/META-INF/com/google/android/update-binary
@@ -581,7 +581,14 @@ nanomod_libs () {
 	else
 		"${INSTALLER}/system/bin/unzip.${BIN_ARCH}" \
 			-oq ${apk} "lib/*" -d "/tmp/nanomod-lib" \
-			2>/dev/null || error " !! installing libs failed"
+			2>/dev/null
+		unzip_return=$?
+		if [ ${unzip_return} -eq 0 ]; then
+			echo "    $(basename ${apk}) does have libs"
+		elif [ ${unzip_return} -eq 11 ]; then
+			echo "    $(basename ${apk}) does not have any libs"
+		else	error " !! installing libs for $(basename ${apk}) failed"
+		fi
 		if [ -d /tmp/nanomod-lib/lib ]; then
 			mkdir -p ${libd}
 			case ${ARCH} in
