Uninstaller (System Mode): restore SecSettings.apk, SecSettings2.apk, com.qualcomm.location if any of those is found backed up

diff --git a/uninstaller/META-INF/com/google/android/update-binary b/uninstaller/META-INF/com/google/android/update-binary
--- a/uninstaller/META-INF/com/google/android/update-binary
+++ b/uninstaller/META-INF/com/google/android/update-binary
@@ -156,6 +156,35 @@ if [ -f /system/.nanomod-list ]; then
 		sed '/\/system\/priv-app\/Settings\/Settings.apk/d' -i /system/.nanomod-list
 	fi
 
+	# SecSettings.apk needs special treament
+	if grep -q /system/priv-app/SecSettings/SecSettings.apk /system/.nanomod-list; then
+		if [ -f /sdcard/SecSettings.apk ]; then
+			ui_print " << restoring: unpatched SecSettings.apk"
+			mv /sdcard/SecSettings.apk /system/priv-app/SecSettings/SecSettings.apk \
+				|| error " !! failed to restore SecSettings.apk"
+		else	ui_print " << can't restore unpatched SecSettings.apk"
+		fi
+		sed '/\/system\/priv-app\/SecSettings\/SecSettings.apk/d' -i /system/.nanomod-list
+	fi
+
+	# SecSettings2.apk needs special treament
+	if grep -q /system/priv-app/SecSettings2/SecSettings2.apk /system/.nanomod-list; then
+		if [ -f /sdcard/SecSettings2.apk ]; then
+			ui_print " << restoring: unpatched SecSettings2.apk"
+			mv /sdcard/SecSettings2.apk /system/priv-app/SecSettings2/SecSettings2.apk \
+				|| error " !! failed to restore SecSettings2.apk"
+		else	ui_print " << can't restore unpatched SecSettings2.apk"
+		fi
+		sed '/\/system\/priv-app\/SecSettings2\/SecSettings2.apk/d' -i /system/.nanomod-list
+	fi
+
+	# com.qualcomm.location needs special treament
+	if [ -d /sdcard/com.qualcomm.location ]; then
+		ui_print " << restoring: com.qualcomm.location"
+		mv /sdcard/com.qualcomm.location /system/priv-app/ \
+			|| error " !! failed to restore com.qualcomm.lcation"
+	fi
+
 	xargs rm -f < /system/.nanomod-list \
 		|| " !! failed to remove files"
 	ui_print " << uninstalling: /system/.nanomod-list"
