fix uninstallation if a previously moved-out GApp exists already in ROM, instead remove the backup

diff --git a/uninstaller/META-INF/com/google/android/update-binary b/uninstaller/META-INF/com/google/android/update-binary
--- a/uninstaller/META-INF/com/google/android/update-binary
+++ b/uninstaller/META-INF/com/google/android/update-binary
@@ -210,13 +210,23 @@ system_mode_uninstall () {
 
 	for app in ${GOOGLE_APPS}; do
 		if [ -d /sdcard/nanodroid_backups/priv-app/${app} ]; then
-			ui_print " << restoring: priv-app / ${app}"
-			mv /sdcard/nanodroid_backups/priv-app/${app} \
-				/system/priv-app/ || error " !! failed to restore ${app}"
+			if [ -d -/system/priv-app/${app} ]; then
+				ui_print " << removing backup: priv-app / ${app}"
+				rm -rf /sdcard/nanodroid_backups/priv-app/${app}
+			else
+				ui_print " << restoring: priv-app / ${app}"
+				mv /sdcard/nanodroid_backups/priv-app/${app} \
+					/system/priv-app/ || error " !! failed to restore ${app}"
+			fi
 		elif [ -d /sdcard/nanodroid_backups/app/${app} ]; then
-			ui_print " << restoring: app / ${app}"
-			mv /sdcard/nanodroid_backups/app/${app} \
-				/system/app/ || error " !! failed to restore ${app}"
+			if [ -d /system/app/${app} ]; then
+				ui_print " << removing backup: app / ${app}"
+				rm -rf /sdcard/nanodroid_backups/app/${app}
+			else
+				ui_print " << restoring: app / ${app}"
+				mv /sdcard/nanodroid_backups/app/${app} \
+					/system/app/ || error " !! failed to restore ${app}"
+			fi
 		fi
 	done
 
